### ISSUE TITLE
Jekyll Template fails to build

### ISSUE THREAD

**Issue by ncphillips** [forestryio/create-static-site#12]
Unfortunately, I pushed a bad commit and broke the Jekyll template 👎 

```[11:04:59] Error in plugin "run-sequence(styles:production)"
Message:
    Invalid glob argument: undefined
Stack:
Error: Invalid glob argument: undefined
    at Gulp.src (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:20:11)
    at Gulp.gulp.task.cb (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/static-scripts/scripts/gulpFile.js:98:6)
    at module.exports (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/run-sequence/index.js:124:15)
    at runSequence (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/run-sequence/index.js:136:2)
    at Gulp.gulp.task.cb (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/static-scripts/scripts/gulpFile.js:88:3)
    at module.exports (/Users/nolan/Code/forestryio/create-static-site/demo/node_modules/orchestrator/lib/runTask.js:34:7)```

**Comment by ncphillips** [comment]
The cause has been found and is being fixed
